---

- name: install docker.io
  package:
    name:
      - docker.io
      - python3-docker
    state: present

- name: enable docker service
  service:
    name: docker
    enabled: yes

- name: initialise docker swarm on first node(the first node is always a manager node)
  docker_swarm:
    state: present
  register: swarm_init_info
  run_once: true # run only on first node and make registered variable avilable to all nodes

- name: join other manager nodes to the swarm(all but first manager node)
  docker_swarm:
    state: join
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    join_token: "{{ swarm_init_info.swarm_facts.JoinTokens.Manager }}"
    remote_addrs: "{{ hostvars[ansible_play_hosts[0]].ansible_facts.default_ipv4.address }}"
  when:
    - dockerswarm_node_role == 'manager'
    - inventory_hostname != ansible_play_hosts_all[0]

- name: join worker nodes to the swarm
  docker_swarm:
    state: join
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    join_token: "{{ swarm_init_info.swarm_facts.JoinTokens.Worker }}"
    remote_addrs: "{{ hostvars[ansible_play_hosts[0]].ansible_facts.default_ipv4.address }}"
  when:
    - dockerswarm_node_role == 'worker'
    - inventory_hostname != ansible_play_hosts_all[0]

#- name: inspect docker swarm
#  docker_swarm:
#    state: inspect
#  register: swarm_info
#
#- debug:
#    var: swarm_info
